spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false # Open Session in View

  datasource:
    url: jdbc:mysql://localhost:3309/study
    username: user
    password: user1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace


server:
  port: 8080